### ISSUE TITLE
Unable to set the game playing

### ISSUE THREAD

**Issue by LeonTG** [stefangeyer/challonge-java#11]
When creating a tournament you can't set the game being played with the tournament query builder and Tournament.setGameName() does not update it on the website

**Comment by stefangeyer** [comment]
This is due to the poor documentation provided by Challonge since the library was implemented following their [docs](https://api.challonge.com/v1/documents/tournaments/create) as a guideline. If the game name is not included in the request params over there, the library cant do it either - I will fix this shortly. If you notice any other missing params / information, please let me know.

**Comment by LeonTG** [comment]
It's in the json on the example below, if that helps, also another thing missing is the match as in progress, unless I'm blind

**Comment by stefangeyer** [comment]
The JSON part below represents the response, the table above the request / query parameters. Could you please elaborate on what's the issue with the matches?

**Comment by LeonTG** [comment]
For matches, on the website you can set a match as in progress so they're highlighted as in progress, I didn't see anything to do that with your api to make that automatic

**Comment by stefangeyer** [comment]
I don't think there is a respective API endpoint for this feature. So unless I am missing somthing this probably can only be done manually. That being said, the documentation and the API in itself is a mess. The API returns very weird things such as a "ham" parameter when you query a tournament. None of those are documented and one can only speculate what they do (and if they are nullable or not). So I wouldn't be suprised if there actually is a way to do this through the API - let me know if you find out.

**Comment by stefangeyer** [comment]
Version `2.0.1` is now available fixing this issue.
